// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.1
// source: goodbye.proto

package goodbyeworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GoodbyeWorld_SayGoodbye_FullMethodName = "/goodbyeworld.GoodbyeWorld/SayGoodbye"
)

// GoodbyeWorldClient is the client API for GoodbyeWorld service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodbyeWorldClient interface {
	SayGoodbye(ctx context.Context, in *GoodbyeRequest, opts ...grpc.CallOption) (*GoodbyeResponse, error)
}

type goodbyeWorldClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodbyeWorldClient(cc grpc.ClientConnInterface) GoodbyeWorldClient {
	return &goodbyeWorldClient{cc}
}

func (c *goodbyeWorldClient) SayGoodbye(ctx context.Context, in *GoodbyeRequest, opts ...grpc.CallOption) (*GoodbyeResponse, error) {
	out := new(GoodbyeResponse)
	err := c.cc.Invoke(ctx, GoodbyeWorld_SayGoodbye_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodbyeWorldServer is the server API for GoodbyeWorld service.
// All implementations must embed UnimplementedGoodbyeWorldServer
// for forward compatibility
type GoodbyeWorldServer interface {
	SayGoodbye(context.Context, *GoodbyeRequest) (*GoodbyeResponse, error)
	mustEmbedUnimplementedGoodbyeWorldServer()
}

// UnimplementedGoodbyeWorldServer must be embedded to have forward compatible implementations.
type UnimplementedGoodbyeWorldServer struct {
}

func (UnimplementedGoodbyeWorldServer) SayGoodbye(context.Context, *GoodbyeRequest) (*GoodbyeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayGoodbye not implemented")
}
func (UnimplementedGoodbyeWorldServer) mustEmbedUnimplementedGoodbyeWorldServer() {}

// UnsafeGoodbyeWorldServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodbyeWorldServer will
// result in compilation errors.
type UnsafeGoodbyeWorldServer interface {
	mustEmbedUnimplementedGoodbyeWorldServer()
}

func RegisterGoodbyeWorldServer(s grpc.ServiceRegistrar, srv GoodbyeWorldServer) {
	s.RegisterService(&GoodbyeWorld_ServiceDesc, srv)
}

func _GoodbyeWorld_SayGoodbye_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GoodbyeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodbyeWorldServer).SayGoodbye(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodbyeWorld_SayGoodbye_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodbyeWorldServer).SayGoodbye(ctx, req.(*GoodbyeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodbyeWorld_ServiceDesc is the grpc.ServiceDesc for GoodbyeWorld service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodbyeWorld_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goodbyeworld.GoodbyeWorld",
	HandlerType: (*GoodbyeWorldServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayGoodbye",
			Handler:    _GoodbyeWorld_SayGoodbye_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goodbye.proto",
}
